### ISSUE TITLE
update to flutter 3.22

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [maximoffua/flutter.nix#15]
Can we somehow overwrite this flutter version part from outside to not need to wait for release here but still have a reproducible version determination?

**Comment by maximoffua** [comment]
You can use [update.py](https://github.com/maximoffua/flutter.nix/blob/main/update/update.py) script to update to latest version locally and run `nix build .`

You can also specify version using `--version` flag (see `--help`)

**Comment by maximoffua** [comment]
Package for Flutter v3.22.1 is released, so I'm closing this issue
