### ISSUE TITLE
Update flutter version

### ISSUE THREAD

**Issue by Prn-Ice** [maximoffua/flutter.nix#3]
Merry Christmas. Is there some way to update the flutter version?

**Comment by ali-yazdanyar** [comment]
merry christmas @Prn-Ice !
u can do that by running this command in terminal :
"flutter upgrade"
and then u should update your flutter packages :
"flutter pub upgrade"

**Comment by Prn-Ice** [comment]
> merry christmas @Prn-Ice !
> u can do that by running this command in terminal :
> "flutter upgrade"
> and then u should update your flutter packages :
> "flutter pub upgrade"

Nix works a little differently, this didnt work.

**Comment by maximoffua** [comment]
Hello @Prn-Ice , I didn't manage to update to 3.16.5. It requires Android SDK during build.
Keep an eye on NixOS/nixpkgs#276050

**Comment by maximoffua** [comment]
Resolved in #5. Updated to the latest stable Flutter v3.16.7
