### ISSUE TITLE
Update stable to 3.19.4

### ISSUE THREAD

**Issue by Tanish2002** [maximoffua/flutter.nix#9]
Currently, the latest stable is set to 3.19.0. Would be appreciated if it's updated to [3.19.4](https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.4-stable.tar.xz) :)

**Comment by maximoffua** [comment]
Yes, you are right. Here is an [update](https://github.com/maximoffua/flutter.nix/releases/tag/3.19.4)

**Comment by Tanish2002** [comment]
Thanks!
